name: DailyChallenge
favicon: null
layout_spectrum: 0.7434
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7f2ee'
    - '#b38a6c'
    - '#000000'
    - '#694934'
    - '#3c210e'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5625
  rhythmicContrast: 0
purpose:
  - name: follow
    item: null
    url: null
